### ISSUE TITLE
IZAR meter under cast-iron cover

### ISSUE THREAD

**Issue by crivchri** [zibous/ha-watermeter#38]
Hi,

I successfully followed your installation instructions and managed to use your recommended solution (ESPHome + AZDelivery ESP32 Dev Kit C V4 + CC1101), to read the consumption of my Diehl IZAR RC I R4 meter.

However I have an issue with reading my IZAR meter, which is located under a cast-iron cover on the road just in front of the house (5 meters).
When the cast-iron cover is open, I can read the meter, but when the cover is closed, no signal is detected by the meter.

What can I do to improve the signal and able to read my water consumption (with the cast-iron cover closed)

Thank you for your help and kind regards.

**Comment by zibous** [comment]
It won't be so easy with a cast-iron cover, because it significantly weakens the signal. 

There are only 2 options for this:

- With the ESP32 as close as possible to the water meter.
- Attach an amplifier antenna to the CCC1101.

It won't work with the normal antenna or a magnetic antenna that only brings little gain.
The simpler solution is to bring the ESP32 close to the water meter so that the data can be read.
